[package]
name = "lexeme-derive"
edition = "2021"
version = "0.0.0"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
quote = "1.0.14"
regex-syntax = "0.6.25"
syn = { version = "1.0.85" }
